[package]
name = "occule"
version = "0.1.0"
edition = "2021"

[features]
default = ["jpg", "png", "lossless"]
jpg = []
png = []
lossless = []

[dependencies]
colored = "2.1.0"
image = "0.24"
img-parts = "0.3.0"
thiserror = "1.0.61"
